config/routes.rb
Rails.application.routes.draw do
  resources :schedules

  resources :users

  resources :courses

  get "examples/index"
  get "examples" => 'examples#index'

  root 'courses#index'
  

end

app/models/course.rb
class Course < ActiveRecord::Base
  validates_presence_of :title, :overview, :duration
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Slimmer::Template
  include Slimmer::SharedTemplates
  slimmer_template 'core_layout'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:title, :overview, :duration)
    end
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  def index
  	@title = 'Examples'
		@has_breadcrumbs = true
		@has_related_links = false
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:date, :location, :status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :digitalproject, :digitalprojectname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :overview %><br>
    <%= f.text_area :overview %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.number_field :duration %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'button' %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Our offerings</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Overview</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= course.overview %></td>
        <td><%= course.duration %></td>
        <td><%= link_to 'View', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Delete', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path, :class => 'button' %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @course.title %>
</p>

<p>
  <strong>Overview:</strong>
  <%= @course.overview %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @course.duration %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/examples/_related_links.html.erb
<!-- related -->
<div class="related-positioning">
<div class="related-container">
<div class="related" id="related">
<div class="inner group related-subsection">
<h2 id="parent-subsection">Related links 1</h2>
<nav role="navigation" aria-labelledby="parent-subsection">

<ul>
<li><a href="/">Link to category</a></li>
<li><a href="/">Link to category</a></li>
<li><a href="/">Link to category</a></li>
<li class="related-topic"><a href="/" title="More in Related links 1">More <span class="visuallyhidden">in Related links 1</span></a></li>
</ul>
</nav>
</div>


<div class="inner group related-section">
<h2 id="parent-section">Related links 2</h2>
<nav role="navigation" aria-labelledby="parent-section">
<ul>
<li><a href="/">Link to parent category</a></li>
<li><a href="/">Link to parent category</a></li>
<li><a href="/">Link to parent category</a></li>
<li class="related-topic"><a href="/" title="More in Related links 2">More <span class="visuallyhidden">in Related links 2</span></a></li>
</ul>
</nav>
</div>

<div class="inner group">
<a class="return-to-top" href="#content">Return to top ↑</a>
</div>

<div id="legacy-sources">
<p>This page replaces</p>
<ul>
<li class="directgov">Directgov</li>
<li class="businesslink">Business Link</li>
</ul>
</div>
</div>
</div>
</div>
<!-- end related -->

app/views/examples/index.html.erb
<h2>Full width</h2>
<p>Donec sed odio dui. Donec id elit non mi porta gravida at eget metus. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ullamcorper nulla non metus auctor fringilla. Aenean lacinia bibendum nulla sed consectetur. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Nullam quis risus eget urna mollis ornare vel eu leo. Aenean lacinia bibendum nulla sed consectetur.</p>

<div class='grid-row'>

	<div class="column-two-thirds">
		<h2>Two thirds</h2>
		<p>Donec sed odio dui. Donec id elit non mi porta gravida at eget metus. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ullamcorper nulla non metus auctor fringilla. Aenean lacinia bibendum nulla sed consectetur. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Nullam quis risus eget urna mollis ornare vel eu leo. Aenean lacinia bibendum nulla sed consectetur.</p>
	</div>

	<div class="column-third">
		<h2>One third</h2>
		<p>Donec sed odio dui. Donec id elit non mi porta gravida at eget metus. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ullamcorper nulla non metus auctor fringilla. Aenean lacinia bibendum nulla sed consectetur. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Nullam quis risus eget urna mollis ornare vel eu leo. Aenean lacinia bibendum nulla sed consectetur.</p>
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title><%= raw(@title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="wrapper">
<%= render partial: 'breadcrumbs' %>

<nav id="proposition-menu" class="no-proposition-name">
  <ul id="proposition-links">
    <li><a class="" href="/government/organisations">Departments</a></li>
    <li><a class="" href="/government/world">Worldwide</a></li>
    <li><a class="" href="/government/how-government-works">How government works</a></li>
    <li><a class="" href="/government/get-involved">Get involved</a></li>
    <li class="clear-child"><a class="active" href="/government/policies">Policies</a></li>
    <li><a class="" href="/government/publications">Publications</a></li>
    <li><a class="" href="/government/publications?publication_filter_option=consultations">Consultations</a></li>
    <li><a class="" href="/government/statistics">Statistics</a></li>
    <li><a class="" href="/government/announcements">Announcements</a></li>
  </ul>
</nav>

<main id="content" role="main">
  
<%= yield %>

</main>
</div>
</body>
</html>

app/views/partials/_report_a_problem.html.erb
<!-- report_a_problem -->
<p class="report-a-problem-toggle js-footer"><a href="">Is there anything wrong with this page?</a></p>
<div class="report-a-problem-container">
<h2>Help us improve GOV.UK</h2>
<form accept-charset="UTF-8" action="/contact/govuk/problem_reports" method="post">
<div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="✓"></div>
<input id="url" name="url" type="hidden" value="https://www.gov.uk/types-of-school"><input id="source" name="source" type="hidden" value=""><input id="page_owner" name="page_owner" type="hidden" value=""><p>Please don't include any personal or financial information,
for example your National Insurance or credit card numbers.</p>

<label for="what_doing">What you were doing</label>
<input id="what_doing" name="what_doing" type="text"><label for="what_wrong">What went wrong</label>
<input id="what_wrong" name="what_wrong" type="text"><div><button name="commit" type="submit" class="button">Send</button></div>

<!--<p>If you have more extensive feedback, please visit the <a href="/feedback">support page</a>.</p>-->
</form>
</div>
<!-- end report_a_problem -->

app/views/schedules/_breadcrumbs.html.erb
<div id="global-breadcrumb">
  <ol role="breadcrumbs" class="group">
  <li><a href="#">Breadcrumb 1</a></li>
  <li><a href="#">Breadcrumb 2</a></li>
  <li><a href="#">Breadcrumb 3</a></li>
  </ol>
</div>

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Schedules aaa bbb</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Location</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.date %></td>
        <td><%= schedule.location %></td>
        <td><%= schedule.status %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @schedule.date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @schedule.location %>
</p>

<p>
  <strong>Status:</strong>
  <%= @schedule.status %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :digitalproject %><br>
    <fieldset class="inline">
	    <label class="block-label" for="digitalproject_yes" data-target="digitalprojectname">
	      <%= radio_button_tag(:digitalproject, "yes") %>
	      Yes
	    </label>
	    <label class="block-label" for="digitalproject_no">
	      <%= radio_button_tag(:digitalproject, "no") %>
	      No
	    </label>
	    <div class="panel-indent js-hidden" id="digitalprojectname">
          <%= f.label :digitalprojectname %><br>
          <%= f.text_field :digitalprojectname %>
        </div>
	 </fieldset>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Digitalproject</th>
      <th>Digitalprojectname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.digitalproject %></td>
        <td><%= user.digitalprojectname %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Digitalproject:</strong>
  <%= @user.digitalproject %>
</p>

<p>
  <strong>Digitalprojectname:</strong>
  <%= @user.digitalprojectname %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>